version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo-data:/data/db

  mysql:
    image: mysql:8.4.2
    container_name: mysql
    command:
      - --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - ./database/sql-data:/var/lib/mysql
      - ./queries/migration/:/docker-entrypoint-initdb.d/
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - mongodb
    restart: always
